start_timer:
  name: Start Timer
  description: Starts a visual countdown timer on a Timerly device.
  target:
    entity:
      domain: timerly
  fields:
    seconds:
      name: Duration (seconds)
      description: The length of the timer in seconds.
      required: true
      default: 30
      selector:
        number:
          min: 1
          max: 7200
          step: 60
          unit_of_measurement: seconds

    type:
      name: Timer Type
      description: Type of timer, which controls the icon and end message.
      required: false
      default: DEFAULT
      selector:
        select:
          options:
            - label: Default
              value: DEFAULT
            - label: Bedtime
              value: BEDTIME
            - label: School
              value: SCHOOL
            - label: Coding
              value: CODING
            - label: Rugby
              value: RUGBY
            - label: Screen Break
              value: SCREEN_BREAK
            - label: Switch Time
              value: SWITCH_TIME
            - label: Car
              value: CAR

    position:
      name: Screen Position
      description: Where the timer should appear on the screen.
      required: false
      default: BottomRight
      selector:
        select:
          options:
            - label: Top Right
              value: TopRight
            - label: Top Left
              value: TopLeft
            - label: Bottom Right
              value: BottomRight
            - label: Bottom Left
              value: BottomLeft
            - label: Center
              value: Center

    voice:
      name: Use Voice
      description: Should the timer speak a message when it ends?
      required: false
      default: true
      selector:
        boolean:


    

    start_time:
      name: Start Time (optional)
      description: Override the timer's start time as a Unix timestamp in milliseconds.
      required: false
      selector:
        number:
          min: 0
          mode: box


cancel_all:
  name: Cancel All
  description: Cancel all active timers and notifications on one or more Timerly devices.
  target:
    entity:
      domain: timerly
  fields:
    target:
      name: Device Name
      required: false

doorbell:
  name: Doorbell Notification
  description: Trigger a doorbell-style alert on all Timerly devices.
  target:
    entity:
      domain: timerly

dismiss:
  name: Dismiss
  description: Dismiss a named notification from all devices.
  target:
    entity:
      domain: timerly
  fields:
    name:
      name: Notification Name
      required: true

set_selected:
  name: Select Timerly Device
  description: Mark a discovered Timerly timer entity as selected or not.
  target:
    entity:
      domain: timerly
  fields:
    target:
      name: Device Name
      required: true
    selected:
      name: Selected
      default: true