name: Create Timerly Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 🔥 ensures tags are available if needed

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install tools
        run: |
          pip install semver
          npm install -g conventional-changelog-cli conventional-recommended-bump

      - name: Determine bump type from commits
        id: bump_type
        run: |
          echo "bump_type=$(npx conventional-recommended-bump -p angular -r 0 | grep '"releaseType":' | cut -d '"' -f4)" >> $GITHUB_OUTPUT

      - name: Bump version in manifest.json
        id: bump
        run: |
          python .github/scripts/bump_version.py ${{ steps.bump_type.outputs.bump_type }}

      - name: Generate changelog section
        run: |
          npx conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Append full compare link to changelog
        run: |
          VERSION="v${{ steps.bump.outputs.new_version }}"
          PREVIOUS="${{ steps.bump.outputs.previous_version }}"
          LINK="[Full Changelog](https://github.com/stquinn/home-assistant-timerly/compare/${PREVIOUS}...${VERSION})"
          sed -i "/## \[$VERSION\]/a\\\n$LINK\n" CHANGELOG.md

      - name: Generate release notes file
        run: |
          VERSION="v${{ steps.bump.outputs.new_version }}"
          DATE=$(date +%Y-%m-%d)
          PREVIOUS="${{ steps.bump.outputs.previous_version }}"
          LINK="🔗 Full Changelog: https://github.com/stquinn/home-assistant-timerly/compare/${PREVIOUS}...${VERSION}"
          echo -e "## [$VERSION] - $DATE\n\n$(npx conventional-changelog -p angular -r 1)\n\n$LINK" > RELEASE_NOTES.md

      - name: Commit version + changelog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add custom_components/timerly/manifest.json CHANGELOG.md
          git commit -m "chore(release): v${{ steps.bump.outputs.new_version }}"
          git push origin HEAD

      - name: Tag version
        run: |
          git tag v${{ steps.bump.outputs.new_version }}
          git push origin v${{ steps.bump.outputs.new_version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.new_version }}
          name: v${{ steps.bump.outputs.new_version }}
          body_path: RELEASE_NOTES.md
