name: Create Timerly Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type (patch, minor, major)'
        required: true
        default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tools
        run: |
          pip install semver

      - name: Bump version
        id: bump
        run: |
          python .github/scripts/bump_version.py ${{ github.event.inputs.version_type }}

      - name: Generate changelog
        run: |
          VERSION="v${{ steps.bump.outputs.new_version }}"
          DATE=$(date +%Y-%m-%d)
          PREVIOUS="${{ steps.bump.outputs.previous_version }}"
      
          {
            echo "## [$VERSION] - $DATE"
            echo
            git log --pretty=format:"- %s" "${PREVIOUS}..HEAD"
            echo
            echo "[Full Changelog](https://github.com/${{ github.repository }}/compare/${PREVIOUS}...${VERSION})"
            echo
          } > temp_changelog.md
      
          cat temp_changelog.md CHANGELOG.md > temp && mv temp CHANGELOG.md



      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add custom_components/timerly/manifest.json CHANGELOG.md
          git commit -m "chore(release): v${{ steps.bump.outputs.new_version }}"
          git push origin HEAD

      - name: Tag new version
        run: |
          git tag v${{ steps.bump.outputs.new_version }}
          git push origin v${{ steps.bump.outputs.new_version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.new_version }}
          name: v${{ steps.bump.outputs.new_version }}
          body: |
            Release v${{ steps.bump.outputs.new_version }}

            🔗 Full Changelog: https://github.com/${{ github.repository }}/compare/${{ steps.bump.outputs.previous_version }}...v${{ steps.bump.outputs.new_version }}
