name: Create HACS Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type (patch, minor, major)'
        required: true
        default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tools
        run: pip install semver

      - name: Bump version and tag
        id: bump
        run: |
          python .github/scripts/bump_version.py ${{ github.event.inputs.version_type }}

      - name: Commit updated manifest.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add custom_components/**/manifest.json
          git commit -m "🔖 Bump version to ${{ steps.bump.outputs.new_version }}"
          git push origin HEAD

      - name: Push new tag
        run: |
          git tag v${{ steps.bump.outputs.new_version }}
          git push origin v${{ steps.bump.outputs.new_version }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.new_version }}
          name: v${{ steps.bump.outputs.new_version }}
          body: |
            Automated release for v${{ steps.bump.outputs.new_version }}
